version: "3.8"

services:
  postgres:
    image: postgres:16  # especifica a versao para mais previsibilidade
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:  
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'lucamesquitaa@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "8081:81"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis_local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_local
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"    # porta AMQP (usada pela aplicação)
      - "15672:15672"  # porta da UI de management (http://localhost:15672)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  cafeteria:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    image: cafeteria:1
    container_name: cafeteria_local
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      PORT: 8080
      CONNECTION_STRING: "Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      jwttoken: ${JWT_SECRET}
      senSiteWeb: ${SEN_SITE_WEB}
      Authentication__Google__ClientId: ${GOOGLE_CLIENT_ID}
      REDIS_HOST: redis:6379
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__Username: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./HMG:/app/HMG:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
       - cafeteria

volumes:
  redis-data:
  rabbitmq-data: