// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaudeIA.Data;

#nullable disable

namespace SaudeIA.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250919003610_cnpj")]
    partial class cnpj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaudeIA.Models.ContatosModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesModelId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SaudeIA.Models.DetalhesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Airpot")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Beach")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Child")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Cleaning")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Coffee")
                        .HasColumnType("boolean");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("CpfRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<bool?>("Downtown")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Gym")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Highway")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Hospital")
                        .HasColumnType("boolean");

                    b.Property<string>("Lobby")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Pets")
                        .HasColumnType("boolean");

                    b.Property<double?>("PetsTax")
                        .HasColumnType("double precision");

                    b.Property<string>("Razao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rede")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Swimming")
                        .HasColumnType("boolean");

                    b.Property<string>("TelRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("SaudeIA.Models.FotosDetalhesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Stared")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesModelId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("SaudeIA.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SaudeIA.Models.UsuarioPermissoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserModelEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("UsuarioPermissao");
                });

            modelBuilder.Entity("SaudeIA.Models.ContatosModel", b =>
                {
                    b.HasOne("SaudeIA.Models.DetalhesModel", null)
                        .WithMany("Contacts")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudeIA.Models.FotosDetalhesModel", b =>
                {
                    b.HasOne("SaudeIA.Models.DetalhesModel", null)
                        .WithMany("Photos")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudeIA.Models.UsuarioPermissoes", b =>
                {
                    b.HasOne("SaudeIA.Models.DetalhesModel", null)
                        .WithMany("Permissions")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaudeIA.Models.UserModel", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudeIA.Models.DetalhesModel", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Permissions");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("SaudeIA.Models.UserModel", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
