// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Turify.Data;

#nullable disable

namespace Turify.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260117114658_resevrahosped")]
    partial class resevrahosped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuartoCategory", b =>
                {
                    b.Property<Guid>("CategoryQuartoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuartosModelId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryQuartoId", "QuartosModelId");

                    b.HasIndex("QuartosModelId");

                    b.ToTable("QuartoCategory");
                });

            modelBuilder.Entity("Turify.Models.CategoryQuarto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesModelId");

                    b.ToTable("CategoryQuarto");
                });

            modelBuilder.Entity("Turify.Models.ContatosModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DetalhesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesId");

                    b.HasIndex("DetalhesModelId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Turify.Models.DTOs.BedsDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BedType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuartosModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuartosModelId");

                    b.ToTable("BedsDTO");
                });

            modelBuilder.Entity("Turify.Models.DetalhesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Airpot")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Beach")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Child")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Cleaning")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Coffee")
                        .HasColumnType("boolean");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("CpfRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<bool?>("Downtown")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Gym")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Highway")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Hospital")
                        .HasColumnType("boolean");

                    b.Property<string>("Lobby")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Pets")
                        .HasColumnType("boolean");

                    b.Property<double?>("PetsTax")
                        .HasColumnType("double precision");

                    b.Property<string>("Razao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rede")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Swimming")
                        .HasColumnType("boolean");

                    b.Property<string>("TelRep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Turify.Models.ErroLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Turify.Models.FotosDetalhesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DetalhesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuartosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuartosModelId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Stared")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesId");

                    b.HasIndex("DetalhesModelId");

                    b.HasIndex("QuartosId");

                    b.HasIndex("QuartosModelId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Turify.Models.Hospedes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("DateBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationId1")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ReservationId1");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("Turify.Models.QuartoAvailable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DayPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuartosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuartosModelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reembolsavel")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("QuartosId");

                    b.HasIndex("QuartosModelId");

                    b.ToTable("QuartoAvailable");
                });

            modelBuilder.Entity("Turify.Models.QuartoReservas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adults")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Checkin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Checkout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cupom")
                        .HasColumnType("text");

                    b.Property<int>("Kids")
                        .HasColumnType("integer");

                    b.Property<double>("PriceTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("QuartosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuartosModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservaStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuartosId");

                    b.HasIndex("QuartosModelId");

                    b.ToTable("QuartoReservas");
                });

            modelBuilder.Entity("Turify.Models.QuartosModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BathProducts")
                        .HasColumnType("text");

                    b.Property<bool?>("Bathroom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Cleaning")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Coffee")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<bool?>("Freeze")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Fridge")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOcupation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<bool?>("Refund")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Telephone")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Tv")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeTv")
                        .HasColumnType("text");

                    b.Property<bool?>("Varanda")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Vault")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesModelId");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("Turify.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Turify.Models.UsuarioPermissoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DetalhesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalhesModelId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserModelEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserModelId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesId");

                    b.HasIndex("DetalhesModelId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserModelId");

                    b.ToTable("UsuarioPermissao");
                });

            modelBuilder.Entity("QuartoCategory", b =>
                {
                    b.HasOne("Turify.Models.CategoryQuarto", null)
                        .WithMany()
                        .HasForeignKey("CategoryQuartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Turify.Models.QuartosModel", null)
                        .WithMany()
                        .HasForeignKey("QuartosModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Turify.Models.CategoryQuarto", b =>
                {
                    b.HasOne("Turify.Models.DetalhesModel", "Detalhes")
                        .WithMany()
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("Turify.Models.ContatosModel", b =>
                {
                    b.HasOne("Turify.Models.DetalhesModel", "Detalhes")
                        .WithMany()
                        .HasForeignKey("DetalhesId");

                    b.HasOne("Turify.Models.DetalhesModel", null)
                        .WithMany("Contacts")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("Turify.Models.DTOs.BedsDTO", b =>
                {
                    b.HasOne("Turify.Models.QuartosModel", null)
                        .WithMany("Beds")
                        .HasForeignKey("QuartosModelId");
                });

            modelBuilder.Entity("Turify.Models.FotosDetalhesModel", b =>
                {
                    b.HasOne("Turify.Models.DetalhesModel", "Detalhes")
                        .WithMany()
                        .HasForeignKey("DetalhesId");

                    b.HasOne("Turify.Models.DetalhesModel", null)
                        .WithMany("Photos")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Turify.Models.QuartosModel", "Quartos")
                        .WithMany()
                        .HasForeignKey("QuartosId");

                    b.HasOne("Turify.Models.QuartosModel", null)
                        .WithMany("Photos")
                        .HasForeignKey("QuartosModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Detalhes");

                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("Turify.Models.Hospedes", b =>
                {
                    b.HasOne("Turify.Models.QuartoReservas", null)
                        .WithMany("Hospede")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Turify.Models.QuartoReservas", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId1");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Turify.Models.QuartoAvailable", b =>
                {
                    b.HasOne("Turify.Models.QuartosModel", "Quartos")
                        .WithMany()
                        .HasForeignKey("QuartosId");

                    b.HasOne("Turify.Models.QuartosModel", null)
                        .WithMany("Disponibilidade")
                        .HasForeignKey("QuartosModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("Turify.Models.QuartoReservas", b =>
                {
                    b.HasOne("Turify.Models.QuartosModel", "Quartos")
                        .WithMany()
                        .HasForeignKey("QuartosId");

                    b.HasOne("Turify.Models.QuartosModel", null)
                        .WithMany("Reservas")
                        .HasForeignKey("QuartosModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("Turify.Models.QuartosModel", b =>
                {
                    b.HasOne("Turify.Models.DetalhesModel", "Detalhes")
                        .WithMany("Quartos")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("Turify.Models.UsuarioPermissoes", b =>
                {
                    b.HasOne("Turify.Models.DetalhesModel", "Detalhes")
                        .WithMany()
                        .HasForeignKey("DetalhesId");

                    b.HasOne("Turify.Models.DetalhesModel", null)
                        .WithMany("Permissions")
                        .HasForeignKey("DetalhesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turify.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Turify.Models.UserModel", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Turify.Models.DetalhesModel", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Permissions");

                    b.Navigation("Photos");

                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("Turify.Models.QuartoReservas", b =>
                {
                    b.Navigation("Hospede");
                });

            modelBuilder.Entity("Turify.Models.QuartosModel", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("Disponibilidade");

                    b.Navigation("Photos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Turify.Models.UserModel", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
